// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgB-jcst5KyA12GwftMI7UjaCBz2f2dLw',
    appId: '1:1008777679414:web:7055003eaaaa965f39be97',
    messagingSenderId: '1008777679414',
    projectId: 'pill-time-93e76',
    authDomain: 'pill-time-93e76.firebaseapp.com',
    storageBucket: 'pill-time-93e76.firebasestorage.app',
    measurementId: 'G-3WBM24GK5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc785pdGurWCFjKtXFyfdZtu_9wIShblU',
    appId: '1:1008777679414:android:241737e13d7f6f3539be97',
    messagingSenderId: '1008777679414',
    projectId: 'pill-time-93e76',
    storageBucket: 'pill-time-93e76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOneDhVnCCjL7DWhvTTFW2xCgPpacGIt8',
    appId: '1:1008777679414:ios:e797fb852374423739be97',
    messagingSenderId: '1008777679414',
    projectId: 'pill-time-93e76',
    storageBucket: 'pill-time-93e76.firebasestorage.app',
    iosBundleId: 'com.example.pillTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOneDhVnCCjL7DWhvTTFW2xCgPpacGIt8',
    appId: '1:1008777679414:ios:e797fb852374423739be97',
    messagingSenderId: '1008777679414',
    projectId: 'pill-time-93e76',
    storageBucket: 'pill-time-93e76.firebasestorage.app',
    iosBundleId: 'com.example.pillTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgB-jcst5KyA12GwftMI7UjaCBz2f2dLw',
    appId: '1:1008777679414:web:959be755192f740939be97',
    messagingSenderId: '1008777679414',
    projectId: 'pill-time-93e76',
    authDomain: 'pill-time-93e76.firebaseapp.com',
    storageBucket: 'pill-time-93e76.firebasestorage.app',
    measurementId: 'G-1D53H7CEZS',
  );
}
